<a href="https://colab.research.google.com/github/NILodio/data-mining/blob/master/Assigment_1_Data_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Collecting, Saving Data, and basic Exploratory Data Analysis (EDA)

In [10]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/NILodio/data-mining/master/init.py
import init; init.init(force_download=False);

replicating local resources

In [11]:
from os import listdir
from os.path import isfile, join

# get the list of file names from the data path
data_path = 'local'
files = [file for file in listdir(data_path) if isfile(join(data_path, file))]
files

['bitcoin.csv',
 'GOOG.csv',
 'APPL.csv',
 'altcoin.csv',
 'Cryptocurrency.csv',
 'coindesk.csv',
 'YHOO.csv',
 'Gold.csv']

In [12]:
import pandas as pd

# function to read multiple csv files from a path into a list of dataframes
def read_csvs_from_path(data_path : str):
    # get list of file names
    files = [file for file in listdir(data_path) if isfile(join(data_path, file))]
    dfs = []

    # loop through files, read the csv file and save the dataframe
    for i, file in enumerate(files):
        df = pd.read_csv(data_path + "/" + file)
        print(str(i+1) + ". Sample data extracted from: '" + file + "'")
        display(df.tail(1))
        dfs.append(df)

    # return the list of dataframes
    return dfs

dfs = read_csvs_from_path(data_path)

1. Sample data extracted from: 'bitcoin.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-10 22:03:06+00:00,1634313959904886786,@JulesXavier9 Obama didn’t take office until 2...,https://twitter.com/btc_liberates/status/16343...,https://twitter.com/btc_liberates

2. Sample data extracted from: 'GOOG.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-05 12:01:20+00:00,1632350581569490946,Get instant updates and free trials join here ...,https://twitter.com/Smith28301/status/16323505...,https://twitter.com/Smith28301

3. Sample data extracted from: 'APPL.csv'

,Datetime,Tweet Id,Text,URL,User
3180,2023-03-05 00:03:31+00:00,1632169937350303744,Apple’s Approval Process Delays Uniswap’s Mobi...,https://twitter.com/ZhotCrypto/status/16321699...,https://twitter.com/ZhotCrypto

4. Sample data extracted from: 'altcoin.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-09 19:03:33+00:00,1633906384160034817,🔔 Public Company Accounting Oversight Board (P...,https://twitter.com/Altcoin_Alerts/status/1633...,https://twitter.com/Altcoin_Alerts

5. Sample data extracted from: 'Cryptocurrency.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-10 14:44:37+00:00,1634203611403022336,Silvergate and Cryptocurrency😣😣,https://twitter.com/tamoinam/status/1634203611...,https://twitter.com/tamoinam

6. Sample data extracted from: 'coindesk.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-06 04:06:30+00:00,1632593471042142213,@milkyway16eth source coindesk - Arca’s Hotz ...,https://twitter.com/hashtronaut207/status/1632...,https://twitter.com/hashtronaut207

7. Sample data extracted from: 'YHOO.csv'

,Datetime,Tweet Id,Text,URL,User
3643,2023-03-05 00:00:48+00:00,1632169253079072768,@NguboAyimbathwa @ChristoThurston @ThuliMadons...,https://twitter.com/Bright_Afrika/status/16321...,https://twitter.com/Bright_Afrika

8. Sample data extracted from: 'Gold.csv'

,Datetime,Tweet Id,Text,URL,User
5000,2023-03-10 22:37:01+00:00,1634322493056905217,Check out Vintage Bracelet Gold Tone Pink Ston...,https://twitter.com/ShopThar/status/1634322493...,https://twitter.com/ShopThar

In [13]:
# function to print a simple line of chars
def print_lines(line:str = '-', n:int = 40):
    # verify parameters type
    if not isinstance(line, str):
        raise ValueError("Parameter 'line' must be a string")
    if not isinstance(n, int):
        raise ValueError("Parameter 'n' must be an int")

    # print the line
    print(line * n)

In [14]:
class EDA:
    def display_shape_and_colnames_df(self, df:pd.DataFrame, return_shape:bool = True):
        # verify parameters type
        if not isinstance(df, pd.DataFrame):
            raise ValueError("Parameter 'df' must be a Pandas DataFrame")
        if not isinstance(return_shape, bool):
            raise ValueError("Parameter 'return_shape' must be a bool")

        # display dataframe shape and column names
        print("Dataframe Rows:", df.shape[0])
        print("Dataframe Columns:", df.shape[1])
        print("Column names:", df.columns.to_list())

        # return the shape if needed
        if return_shape: return df.shape

    def display_shape_and_colnames_dfs(self, dfs:list, names:list):
        # verify parameters type
        if not isinstance(dfs, list):
            raise ValueError("Parameter 'dfs' must be a list")
        if not isinstance(names, list):
            raise ValueError("Parameter 'names' must be a list")
        assert len(names) == len(dfs), "'dfs' and 'names' must have same length"

        # display
        total_rows = 0
        for i, df in enumerate(dfs):
            print("Dataframe from file:", names[i])
            df_shape = self.display_shape_and_colnames_df(df)
            total_rows += df_shape[0]
            print_lines()
        print("TOTAL ROWS:", total_rows)

eda = EDA()
eda.display_shape_and_colnames_dfs(dfs, files)

Dataframe from file: bitcoin.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: GOOG.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: APPL.csv
Dataframe Rows: 3181
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: altcoin.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: Cryptocurrency.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: coindesk.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: YHOO.csv
Dataframe Rows: 3644
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
Dataframe from file: Gold.csv
Dataframe Rows: 5001
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']
----------------------------------------
TOTAL ROWS: 36831

In [15]:
# applying a vertical concat on all our datasets
df = pd.concat(dfs, axis=0).reset_index(drop=True)
df.tail()

,Datetime,Tweet Id,Text,URL,User
36826,2023-03-10 22:37:03+00:00,1634322503807176704,@chigrl @cvpayne Gold. Silver. Nat gas. Oil.,https://twitter.com/p3eichler/status/163432250...,https://twitter.com/p3eichler
36827,2023-03-10 22:37:02+00:00,1634322499063144451,"@katekiewel In a Mexican bank, they have these...",https://twitter.com/mendezcarlos24/status/1634...,https://twitter.com/mendezcarlos24
36828,2023-03-10 22:37:01+00:00,1634322495187845123,@KAZU82155582 かず兄ちゃん、おはようです☀️\n7連勤中の何日目だったかしら？...,https://twitter.com/pink_gold_miya/status/1634...,https://twitter.com/pink_gold_miya
36829,2023-03-10 22:37:01+00:00,1634322494525177856,"me to the waiter: excuse me, my onion rings?Th...",https://twitter.com/PamelaG07125515/status/163...,https://twitter.com/PamelaG07125515
36830,2023-03-10 22:37:01+00:00,1634322493056905217,Check out Vintage Bracelet Gold Tone Pink Ston...,https://twitter.com/ShopThar/status/1634322493...,https://twitter.com/ShopThar

In [16]:
eda.display_shape_and_colnames_df(df, return_shape=False)

Dataframe Rows: 36831
Dataframe Columns: 5
Column names: ['Datetime', 'Tweet Id', 'Text', 'URL', 'User']

In [17]:
class EDA_2():
    def check_missing_values_df(self, df : pd.DataFrame):
        # verify parameters type
        if not isinstance(df, pd.DataFrame):
            raise ValueError("Parameter 'df' must be a Pandas DataFrame")

        # display missing values per column
        print("# Missing values per column:")
        display(df.isna().sum())
        print_lines(n=30)
        print("% Missing values per column:")
        display(df.isna().mean() * 100)
        print_lines(n=30)

    def check_duplicated_rows_df(self, df : pd.DataFrame):
        # verify parameters type
        if not isinstance(df, pd.DataFrame):
            raise ValueError("Parameter 'df' must be a Pandas DataFrame")

        # display duplicates from the dataset
        print("# Duplicated rows:", df.duplicated().sum())
        print_lines(n=30)
        print("% Duplicated rows:", round(df.duplicated().mean() * 100, 2))
        print_lines(n=30)

    def check_unique_values_df(self,df : pd.DataFrame):
        # verify parameters type
        if not isinstance(df, pd.DataFrame):
            raise ValueError("Parameter 'df' must be a Pandas DataFrame")

        # display unique values per column
        print("# Unique values per column:")
        display(df.nunique())
        print_lines(n=30)
        print("% Unique values per column (relative to total rows):")
        display(round(df.nunique()*100 / df.shape[0], 2))
        print_lines(n=30)

eda = EDA_2()
eda.check_missing_values_df(df)
eda.check_duplicated_rows_df(df)
eda.check_unique_values_df(df)

# Missing values per column:

Datetime    0
Tweet Id    0
Text        0
URL         0
User        0
dtype: int64

------------------------------
% Missing values per column:

Datetime    0.0
Tweet Id    0.0
Text        0.0
URL         0.0
User        0.0
dtype: float64

------------------------------
# Duplicated rows: 460
------------------------------
% Duplicated rows: 1.25
------------------------------
# Unique values per column:

Datetime    29029
Tweet Id    36371
Text        35661
URL         36371
User        18564
dtype: int64

------------------------------
% Unique values per column (relative to total rows):

Datetime    78.82
Tweet Id    98.75
Text        96.82
URL         98.75
User        50.40
dtype: float64

------------------------------

### 2. Cleaning Data